### ISSUE TITLE
can't find 'Node' binary ?

### ISSUE THREAD

**Issue by mtissington** [jun6lee/Alfred-WordSearch#1]
<img width="577" alt="image" src="https://user-images.githubusercontent.com/6769116/170798949-4e96e4f5-da70-4f23-93b6-6edc308713de.png">

**Comment by jun6lee** [comment]
I think the answer is within the screenshot.
You need to symlink your node to /usr/local/bin	

`ln -s /usr/local/bin/node node`

**Comment by mtissington** [comment]
Hmm, not idea what 'node' it was talking about.
However the issue seems to have resolved itself without me doing anything.
