### ISSUE TITLE
SSL CERTIFICATE

### ISSUE THREAD

**Issue by chronoclasm** [jun6lee/Alfred-WordSearch#5]
Sorry for a newbie question, but

When I installed and used this workflow, I got

<urlopen error [SSL_CERTIFICATE_VERIFY_FAILED] ...

What do I do?

**Comment by gtgpee** [comment]
This worked for me- 
https://stackoverflow.com/questions/68275857/urllib-error-urlerror-urlopen-error-ssl-certificate-verify-failed-certifica

In short, I used Finder to search for, then ran ""Install Certificates.command" in my python folder
